### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by zxp19821005** [MooudMohammady/electron-deno-IDE#1]
I've ported the package to AUR,this is the link:https://aur.archlinux.org/packages/electron-deno-ide
I've some suggestions about it.
### package.json
Please move `"electron-builder": "^24.6.3"` from `dependencies` section to `devDependencies` section,when I ported the package,I got this errors:
```
> electron-builder

  • electron-builder  version=24.6.3 os=6.1.57-1-lts
  • loaded configuration  file=/home/zxp-endeavouros/.cache/paru/clone/electron-deno-ide/src/electron-deno-IDE-0.1.1-beta/electron-builder.json5
  ⨯ Package "electron-rebuild" is only allowed in "devDependencies". Please remove it from the "dependencies" section in your package.json.
```
### electron-builder.json5
Maybe you can try to add Linux support in it,what I do was that:
```
sed 's|win|linux|g;s|"nsis",|"AppImage",|g'
```
### Other
When I run the package,there was no program's icon on the taskbar,it was just an unknown icon.

**Comment by MooudMohammady** [comment]
Thank you for your assistance. I appreciate your help, and I'll definitely incorporate the changes you suggested. However, at the moment, I'm not actively working on this project.🙏
